config/routes.rb
LeagueStats::Application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get "/dashboard", to: "users#show", as: :dashboard
  resources :users, except: :show

  get "/:server/:riot_id", to: "summoners#show", as: :summoner
  # get "/:server/:riot_id/edit", to: "summoners#edit", as: :edit_summoner
  # patch "/:server/:riot_id", to: "summoners#update"
  # put "/:server/:riot_id", to: "summoners#update"
  delete "/:server/:riot_id", to: "summoners#destroy"
  resources :summoners, except: [:show, :edit, :update, :destroy]

  get "/:server/:riot_id/:game_num", to: "games#show", as: :game
  # get "/:server/:riot_id/:game_num/edit", to: "games#edit", as: :edit_game
  # patch "/:server/:riot_id/:game_num", to: "games#update"
  # put "/:server/:riot_id/:game_num", to: "games#update"
  delete "/:server/:riot_id/:game_num", to: "games#destroy"
  resources :games, except: [:show, :edit, :update, :destroy]
end

app/models/summoner.rb
class Summoner < ActiveRecord::Base
  has_many :ownerships
  has_many :users, through: :ownerships
  has_many :games
  validates :level, presence: true
end

app/controllers/summoners_controller.rb
class SummonersController < ApplicationController
  before_action :set_summoner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_unirest_header

  # GET /summoners
  # GET /summoners.json
  def index
    @summoners = Summoner.all
  end

  # GET /summoners/1
  # GET /summoners/1.json
  def show
    @game = @summoner.games.new
    @games = @summoner.games.order(game_num: :desc)
  end

  # GET /summoners/new
  def new
    @summoner = current_user.summoners.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /summoners/1/edit
  # def edit
  # end

  # POST /summoners
  # POST /summoners.json
  def create
    @user = current_user
    # @summoner = Summoner.new(summoner_params)
    @summoners = current_user.summoners.order(updated_at: :desc)

    server = params[:summoner][:server].downcase
    name = params[:summoner][:name].downcase

    @summoner = Summoner.where(server: server, name: name).first_or_initialize

    if Ownership.where(summoner_id: @summoner.id, user_id: current_user.id).empty?
      search_string = "https://teemojson.p.mashape.com/player/#{server}/#{name}"
      response = Unirest.get(search_string).body["data"]

      if response.present?
        @summoner.icon = response["icon"]
        @summoner.level = response["level"]
        @summoner.riot_id = response["summonerId"]
      end

      search_string = "https://teemojson.p.mashape.com/player/#{server}/#{name}/honor"
      response = Unirest.get(search_string).body["data"]

      if response.present?
        @summoner.honor_friendly = response["totals"][1]
        @summoner.honor_helpful = response["totals"][2]
        @summoner.honor_teamwork = response["totals"][3]
        @summoner.honor_opponent = response["totals"][4]
      end

      search_string = "https://teemojson.p.mashape.com/player/#{server}/#{name}/influence_points"
      response = Unirest.get(search_string).body["data"]

      if response.present?
        @summoner.lifetime_ip = response
      end

      search_string = "https://teemojson.p.mashape.com/player/#{server}/#{name}/past_seasons"
      response = Unirest.get(search_string).body["data"]

      if response.present?
        @summoner.last_season = response["seasonTwo"]
      end

      respond_to do |format|
        if @summoner.save
          @user.summoners << @summoner
          format.html { redirect_to summoner_path(@summoner.server, @summoner.riot_id), notice: 'Summoner was successfully created.' }
          format.json { render action: 'show', status: :created, location: @summoner }
          format.js
          return
        else
          format.html { render action: 'new' }
          format.json { render json: @summoner.errors, status: :unprocessable_entity }
          format.js
          return
        end
      end
    end

    @summoner = Summoner.new

    respond_to do |format|
      format.html { redirect_to summoner_path(@summoner.server, @summoner.riot_id), notice: 'Summoner was successfully created.' }
      format.json { render action: 'show', status: :created, location: @summoner }
      format.js
      return
    end
  end

  # PATCH/PUT /summoners/1
  # PATCH/PUT /summoners/1.json
  # def update
  #   respond_to do |format|
  #     if @summoner.update(summoner_params)
  #       format.html { redirect_to @summoner, notice: 'Summoner was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @summoner.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /summoners/1
  # DELETE /summoners/1.json
  def destroy
    @summoner.destroy
    respond_to do |format|
      format.html { redirect_to summoners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_summoner
      @summoner = Summoner.where(:riot_id=>params[:riot_id]).where(:server=>params[:server]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def summoner_params
      params.require(:summoner).permit(:name, :level, :icon, :server, :honor_friendly, :honor_helpful, :honor_teamwork, :honor_opponent, :lifetime_ip, :last_season, :riot_id)
    end

    def set_unirest_header
      Unirest.default_header("X-Mashape-Authorization",ENV['MASHAPE_KEY'])
    end
end

app/helpers/summoners_helper.rb
module SummonersHelper
end

app/views/summoners/_form.html.erb
<%= minimal_form_for @summoner, remote: true do |f| %>
  <%= f.error_notification %>

<div class="row collapse">
  <div class="small-4 large-offset-2 columns">
    <%= f.input :name %>
  </div>
  <div class="small-3 columns">
    <%= f.input :server, collection: %w{ NA EUW EUN BR RU TR LAS LAN OC }, include_blank: false %>
  </div>
  <div class="small-1 columns end">
    <%= f.button :button do %>
      <i class="fi-magnifying-glass large"></i>
    <% end %>
  </div>
</div>
<% end %>

app/views/summoners/_summoner.html.erb
<div class="summoner panel radius">
  <h3 class="small-3"><%= link_to summoner.name.titleize, summoner_path(summoner.server, summoner.riot_id) %></h3>
  <p>Server: <%= summoner.server.upcase %> | Level: <%= summoner.level %></p>
</div>

app/views/summoners/edit.html.erb
<h1>Editing summoner</h1>

<%= render 'form' %>

<%= link_to 'Show', summoner_path(@summoner.server, @summoner.name) %> |
<%= link_to 'Back', summoners_path %>

app/views/summoners/index.html.erb
<h1>Listing summoners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Icon</th>
      <th>Server</th>
      <th>Honor friendly</th>
      <th>Honor helpful</th>
      <th>Honor teamwork</th>
      <th>Honor opponent</th>
      <th>Lifetime ip</th>
      <th>Last season</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @summoners.each do |summoner| %>
      <tr>
        <td><%= summoner.name %></td>
        <td><%= summoner.level %></td>
        <td><%= summoner.icon %></td>
        <td><%= summoner.server %></td>
        <td><%= summoner.honor_friendly %></td>
        <td><%= summoner.honor_helpful %></td>
        <td><%= summoner.honor_teamwork %></td>
        <td><%= summoner.honor_opponent %></td>
        <td><%= summoner.lifetime_ip %></td>
        <td><%= summoner.last_season %></td>
        <td><%= link_to 'Show', summoner_path(summoner.server, summoner.name) %></td>
        <td><%= link_to 'Destroy', summoner_path(summoner.server, summoner.name), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Summoner', new_summoner_path %>

app/views/summoners/new.html.erb
<h1>New summoner</h1>

<%= render 'form' %>

<%= link_to 'Back', summoners_path %>

app/views/summoners/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', dashboard_path %>
<br />
<br />
<% if @summoner %>
  <h1><%= @summoner.name.titleize %></h1>

  <p>Server -  <%= @summoner.server.upcase %></p>
  <p>Level -  <%= @summoner.level %></p>
  <!-- <p>Last season's rank - <%#= @summoner.last_season.titleize %></p> -->
  <p>Lifetime IP - <%= @summoner.lifetime_ip %></p>
  <p>Honor:</p>
  <table class="text-center">
    <thead>
      <tr>
        <th>Friendly</th>
        <th>Helpful</th>
        <th>Teamwork</th>
        <th>Honorable Opponent</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @summoner.honor_friendly %></td>
        <td><%= @summoner.honor_helpful %></td>
        <td><%= @summoner.honor_teamwork %></td>
        <td><%= @summoner.honor_opponent %></td>
      </tr>
    </tbody>
  </table>

  <br />

  <%= minimal_form_for @game, remote: true, url: games_path(server: @summoner.server, name: @summoner.name) do |f| %>
    <%= f.error_notification %>

    <%= f.input :summoner_id, input_html: { value: @summoner.id }, as: :hidden %>

    <div class="form-actions">
      <%= f.button :button, 'Update Match History' %>
    </div>
  <% end %>
<% end %>

<h3>Match History</h3>
<div id="loading"></div>
<div id="match_history">
  <% if @games.empty? %>
    <p class="no_games">It's empty!</p>
  <% else %>
    <%= render @games %>
  <% end %>
</div>