config/routes.rb
LeagueStats::Application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get "/dashboard", to: "users#show", as: :dashboard
  resources :users, except: :show

  get "/:server/:riot_id", to: "summoners#show", as: :summoner
  # get "/:server/:riot_id/edit", to: "summoners#edit", as: :edit_summoner
  # patch "/:server/:riot_id", to: "summoners#update"
  # put "/:server/:riot_id", to: "summoners#update"
  delete "/:server/:riot_id", to: "summoners#destroy"
  resources :summoners, except: [:show, :edit, :update, :destroy]

  get "/:server/:riot_id/:game_num", to: "games#show", as: :game
  # get "/:server/:riot_id/:game_num/edit", to: "games#edit", as: :edit_game
  # patch "/:server/:riot_id/:game_num", to: "games#update"
  # put "/:server/:riot_id/:game_num", to: "games#update"
  delete "/:server/:riot_id/:game_num", to: "games#destroy"
  resources :games, except: [:show, :edit, :update, :destroy]
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :summoner
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :destroy]
  before_action :set_summoner, only: :create
  before_action :set_unirest_header

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  # def edit
  # end

  # POST /games
  # POST /games.json
  def create
    server = params[:server]
    name = params[:name]

    search_string = "https://teemojson.p.mashape.com/player/#{server}/#{name}/recent_games"
    response = Unirest.get(search_string).body["data"]

    sorted_game_nums = response["playerGameStatsMap"].keys.sort_by(&:to_i)
    game_stats = response["gameStatistics"]["array"]

    saved_games = []
    discarded_games = []

    if response.present?
      for num in sorted_game_nums
        for game in game_stats
          if num.to_i == game["gameId"] && (game["queueType"] == "RANKED_SOLO_5x5" || game["queueType"] == "NORMAL")
            @game = Game.where(game_num: game["gameId"], summoner_id: params[:game][:summoner_id]).first_or_initialize
            @game.game_num = game["gameId"]
            @game.ip_earned = game["ipEarned"]
            @game.ping = game["userServerPing"]
            @game.time_in_queue = game["timeInQueue"]
            @game.champion_id = game["championId"]
            @game.queue_type = game["queueType"]
            @game.spell_one = game["spell1"]
            @game.spell_two = game["spell2"]
            @game.team_id = game["teamId"]
            @game.create_date = DateTime.parse(game["createDate"])

            stats = game["statistics"]["array"]

            for stat in stats
              case stat["statType"]
              when "WIN" then @game.win = true
              when "LOSE" then @game.win = false
              when "ITEM0" then @game.item_zero = stat["value"]
              when "ITEM1" then @game.item_one = stat["value"]
              when "ITEM2" then @game.item_two = stat["value"]
              when "ITEM3" then @game.item_three = stat["value"]
              when "ITEM4" then @game.item_four = stat["value"]
              when "ITEM5" then @game.item_five = stat["value"]
              when "ITEM6" then @game.item_six = stat["value"]
              when "CHAMPIONS_KILLED" then @game.champions_killed = stat["value"]
              when "NUM_DEATHS" then @game.num_deaths = stat["value"]
              when "ASSISTS" then @game.assists = stat["value"]
              when "GOLD_EARNED" then @game.gold_earned = stat["value"]
              when "LEVEL" then @game.level = stat["value"]
              when "MINIONS_KILLED" then @game.minions_killed = stat["value"]
              when "NEUTRAL_MINIONS_KILLED" then @game.neutral_minions_killed = stat["value"]
              when "NEUTRAL_MINIONS_KILLED_YOUR_JUNGLE" then @game.neutral_minions_killed_your_jungle = stat["value"]
              when "NEUTRAL_MINIONS_KILLED_ENEMY_JUNGLE" then @game.neutral_minions_killed_enemy_jungle = stat["value"]              
              when "LARGEST_MULTI_KILL" then @game.largest_multi_kill = stat["value"]
              when "LARGEST_KILLING_SPREE" then @game.largest_killing_spree = stat["value"]
              when "TOTAL_DAMAGE_DEALT" then @game.total_damage_dealt = stat["value"]
              when "TRUE_DAMAGE_DEALT_PLAYER" then @game.true_damage_dealt_player = stat["value"]
              when "MAGIC_DAMAGE_DEALT_PLAYER" then @game.magic_damage_dealt_player = stat["value"]
              when "PHYSICAL_DAMAGE_DEALT_PLAYER" then @game.physical_damage_dealt_player = stat["value"]
              when "TOTAL_DAMAGE_DEALT_TO_CHAMPIONS" then @game.total_damage_dealt_to_champions = stat["value"]
              when "TRUE_DAMAGE_DEALT_TO_CHAMPIONS" then @game.true_damage_dealt_to_champions = stat["value"]
              when "MAGIC_DAMAGE_DEALT_TO_CHAMPIONS" then @game.magic_damage_dealt_to_champions = stat["value"]
              when "PHYSICAL_DAMAGE_DEALT_TO_CHAMPIONS" then @game.physical_damage_dealt_to_champions = stat["value"]
              when "TOTAL_DAMAGE_TAKEN" then @game.total_damage_taken = stat["value"]
              when "TRUE_DAMAGE_TAKEN" then @game.true_damage_taken = stat["value"]
              when "MAGIC_DAMAGE_TAKEN" then @game.magic_damage_taken = stat["value"]
              when "PHYSICAL_DAMAGE_TAKEN" then @game.physical_damage_taken = stat["value"]
              when "TOTAL_HEAL" then @game.total_heal = stat["value"]
              when "TOTAL_TIME_CROWD_CONTROL_DEALT" then @game.total_time_crowd_control_dealt = stat["value"]
              when "TOTAL_TIME_SPENT_DEAD" then @game.total_time_spent_dead = stat["value"]
              when "WARD_PLACED" then @game.ward_placed = stat["value"]
              when "SIGHT_WARDS_BOUGHT_IN_GAME" then @game.sight_wards_bought_in_game = stat["value"]
              end
              @game.champions_killed ||= 0
              @game.num_deaths ||= 0
              @game.assists ||= 0
            end
            if @game.save
              saved_games.push(num)
            else
              discarded_games.push(num)
            end
          end
        end
      end
    end

    @games = Game.where(summoner_id: params[:game][:summoner_id]).order(game_num: :desc)

    respond_to do |format|
      # if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
        format.js
      # else
      #   format.html { render action: 'new' }
      #   format.json { render json: @game.errors, status: :unprocessable_entity }
      #   format.js
      # end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  # def update
  #   respond_to do |format|
  #     if @game.update(game_params)
  #       format.html { redirect_to @game, notice: 'Game was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @game.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @summoner = Summoner.where(:riot_id=>params[:riot_id]).where(:server=>params[:server]).first
      @game = @summoner.games.where(:game_num=>params[:game_num]).first
    end

    def set_summoner
      @summoner = Summoner.where(:riot_id=>params[:riot_id]).where(:server=>params[:server]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:summoner_id, :game_num, :ip_earned, :ping, :time_in_queue, :champion_id, :queue_type, :create_date, :spell_one, :spell_two, :team_id, :neutral_minions_killed_enemy_jungle, :true_damage_dealt_to_champions, :total_heal, :ward_placed, :assists, :total_damage_dealt_to_champions, :true_damage_taken, :num_deaths, :largest_killing_spree, :magic_damage_dealt_player, :true_damage_dealt_player, :item_four, :physical_damage_dealt_player, :largest_multi_kill, :item_two, :neutral_minions_killed_your_jungle, :physical_damage_taken, :total_damage_taken, :minions_killed, :champions_killed, :item_one, :magic_damage_taken, :physical_damage_dealt_to_champions, :item_five, :gold_earned, :magic_damage_dealt_to_champions, :item_six, :total_time_spent_dead, :neutral_minions_killed, :level, :item_zero, :total_damage_dealt, :sight_wards_bought_in_game, :total_time_crowd_control_dealt, :win)
    end

    def set_unirest_header
      Unirest.default_header("X-Mashape-Authorization",ENV['MASHAPE_KEY'])
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= minimal_form_for @game, remote: true do |f| %>
  <%= f.error_notification %>

  <div class="form-actions">
    <%= f.button :button, 'Update Match History' %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div class="game_wrapper panel radius">
  <span class="champion_pic"><%= link_to image_tag("http://league-stats.s3.amazonaws.com/champions/#{get_champion_name game.champion_id}_Square_0.png", height: '64', width: '64'), game_path(game.summoner.server, game.summoner.riot_id, game.game_num)%></span>
  <% if game.win? %>
    <span class="result win text-center">WIN</span>
  <% else %>
    <span class="result loss text-center">LOSS</span>
  <% end %>
  <span class="queue_type"><%= game.queue_type.titleize %></span>
  <span class="kda">KDA: <%= game.champions_killed %>/<%= game.num_deaths %>/<%= game.assists %></span>
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Game num</th>
      <th>Summoner</th>
      <th>Queue type</th>
      <th>Win</th>
      <th>Champion</th>
      <th>Kills</th>
      <th>Deaths</th>
      <th>Assists</th>
      <th>Item zero</th>
      <th>Item one</th>
      <th>Item two</th>
      <th>Item three</th>
      <th>Item four</th>
      <th>Item five</th>
      <th>Item six</th>
      <th>Spell one</th>
      <th>Spell two</th>
      <th>Create date</th>
      <th>Team</th>
      <th>Ip earned</th>
      <th>Ping</th>
      <th>Time in queue</th>
      <th>Gold earned</th>
      <th>Level</th>
      <th>Minions killed</th>
      <th>Neutral minions killed</th>
      <th>Neutral minions killed your jungle</th>
      <th>Neutral minions killed enemy jungle</th>
      <th>Largest multi kill</th>
      <th>Largest killing spree</th>
      <th>Total damage dealt</th>
      <th>True damage dealt player</th>
      <th>Magic damage dealt player</th>
      <th>Physical damage dealt player</th>
      <th>Total damage dealt to champions</th>
      <th>True damage dealt to champions</th>
      <th>Magic damage dealt to champions</th>
      <th>Physical damage dealt to champions</th>
      <th>Total damage taken</th>
      <th>True damage taken</th>
      <th>Magic damage taken</th>
      <th>Physical damage taken</th>
      <th>Total heal</th>
      <th>Total time crowd control dealt</th>
      <th>Total time spent dead</th>
      <th>Ward placed</th>
      <th>Sight wards bought in game</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.game_num, game_path(game.summoner.server, game.summoner.name, game.game_num) %></td>
        <td><%= game.summoner.name %></td>
        <td><%= game.queue_type %></td>
        <td><%= game.win %></td>
        <td><%= get_champion_name game.champion_id %></td>
        <td><%= game.champions_killed %></td>
        <td><%= game.num_deaths %></td>
        <td><%= game.assists %></td>
        <td><%= get_item_name game.item_zero %></td>
        <td><%= get_item_name game.item_one %></td>
        <td><%= get_item_name game.item_two %></td>
        <td><%= get_item_name game.item_three %></td>
        <td><%= get_item_name game.item_four %></td>
        <td><%= get_item_name game.item_five %></td>
        <td><%= get_item_name game.item_six %></td>
        <td><%= get_summoner_spell_name game.spell_one %></td>
        <td><%= get_summoner_spell_name game.spell_two %></td>
        <td><%= game.create_date %></td>
        <td><%= game.team_id %></td>
        <td><%= game.ip_earned %></td>
        <td><%= game.ping %></td>
        <td><%= game.time_in_queue %></td>
        <td><%= game.gold_earned %></td>
        <td><%= game.level %></td>
        <td><%= game.minions_killed %></td>
        <td><%= game.neutral_minions_killed %></td>
        <td><%= game.neutral_minions_killed_your_jungle %></td>
        <td><%= game.neutral_minions_killed_enemy_jungle %></td>
        <td><%= game.largest_multi_kill %></td>
        <td><%= game.largest_killing_spree %></td>
        <td><%= game.total_damage_dealt %></td>
        <td><%= game.true_damage_dealt_player %></td>
        <td><%= game.magic_damage_dealt_player %></td>
        <td><%= game.physical_damage_dealt_player %></td>
        <td><%= game.total_damage_dealt_to_champions %></td>
        <td><%= game.true_damage_dealt_to_champions %></td>
        <td><%= game.magic_damage_dealt_to_champions %></td>
        <td><%= game.physical_damage_dealt_to_champions %></td>
        <td><%= game.total_damage_taken %></td>
        <td><%= game.true_damage_taken %></td>
        <td><%= game.magic_damage_taken %></td>
        <td><%= game.physical_damage_taken %></td>
        <td><%= game.total_heal %></td>
        <td><%= game.total_time_crowd_control_dealt %></td>
        <td><%= game.total_time_spent_dead %></td>
        <td><%= game.ward_placed %></td>        
        <td><%= game.sight_wards_bought_in_game %></td>
        <td><%= link_to 'Show', game_path(game.summoner.server, game.summoner.name, game.game_num) %></td>
        <td><%= link_to 'Destroy', game_path(game.summoner.server, game.summoner.name, game.game_num), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', summoner_path(@summoner.server, @summoner.riot_id) %>

<br />
<br />

<%= image_tag("http://league-stats.s3.amazonaws.com/champions/#{get_champion_name @game.champion_id}_Square_0.png", height: '64', width: '64') %>
<% if @game.win? %>
  <span class="result win text-center">WIN</span>
<% else %>
  <span class="result loss text-center">LOSS</span>
<% end %>
<span class="queue_type"><%= @game.queue_type.titleize %></span>
<span class="kda">KDA: <%= @game.champions_killed %>/<%= @game.num_deaths %>/<%= @game.assists %></span>
<% if @game.team_id == 100 %>
  <span class="team">Team One</span>
<% elsif @game.team_id == 200 %>
  <span class="team">Team Two</span>
<% end %>

<br />
<br />

<p><%= @game.create_date.strftime("Created at %r on %m/%d/%Y") %></p>

<p>
  <span class="ip">Ip earned: <%= @game.ip_earned %></span>
  <span class="ping">Ping: <%= @game.ping %></span>
  <span class="time_in_queue">Time in queue: <%= @game.time_in_queue %></span>
</p>


<h3>Items</h3>
<p>
  <span class="first_item"><%= get_item_name @game.item_zero %></span>
  <span class="item"><%= get_item_name @game.item_one %></span>
  <span class="item"><%= get_item_name @game.item_two %></span>
  <span class="item"><%= get_item_name @game.item_three %></span>
  <span class="item"><%= get_item_name @game.item_four %></span>
  <span class="item"><%= get_item_name @game.item_five %></span>
  <span class="item"><%= get_item_name @game.item_six %></span>
</p>

<h4>Summoner Spells</h4>
<p>
  <span><%= get_summoner_spell_name @game.spell_one %></span>
  <span class="spell"><%= get_summoner_spell_name @game.spell_two %></span>
</p>

<p>
  <span class="level">Level: <%= @game.level %></span>
  <span class="gold_earned">Gold earned: <%= @game.gold_earned %></span>
  <span class="minions">Minions killed: <%= @game.minions_killed %></span>
</p>

<p>
  <span>Largest killing spree: <%= @game.largest_killing_spree %></span>
  <span class="multikill">Largest multikill: <%= @game.largest_multi_kill %></span>
</p>

<p>
  <span>Time spent dead: <%= @game.total_time_spent_dead %> secs</span>
  <span class="cc">Crowd control dealt: <%= @game.total_time_crowd_control_dealt %> secs</span>
</p>

<p>
  <span>Sight wards bought in game: <%= @game.sight_wards_bought_in_game %></span>
  <span class="wards">Wards placed: <%= @game.ward_placed %></span>
</p>

<table class="text-center">
  <thead>
    <tr>
      <th></th>
      <th>Damage Done</th>
      <th>to Champions</th>
      <th>Damage Taken</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Total damage</td>
      <td><%= @game.total_damage_dealt %></td>
      <td><%= @game.total_damage_dealt_to_champions %></td>
      <td><%= @game.total_damage_taken %></td>
    </tr>
    <tr>
      <td>True damage</td>
      <td><%= @game.true_damage_dealt_player %></td>
      <td><%= @game.true_damage_dealt_to_champions %></td>
      <td><%= @game.true_damage_taken %></td>
    </tr>
    <tr>
      <td>Magic damage</td>
      <td><%= @game.magic_damage_dealt_player %></td>
      <td><%= @game.magic_damage_dealt_to_champions %></td>
      <td><%= @game.magic_damage_taken %></td>
    </tr>
    <tr>
      <td>Physical damage</td>
      <td><%= @game.physical_damage_dealt_player %></td>
      <td><%= @game.physical_damage_dealt_to_champions %></td>
      <td><%= @game.physical_damage_taken %></td>
    </tr>
  </tbody>
</table>