config/routes.rb
LeagueStats::Application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get "/dashboard", to: "users#show", as: :dashboard
  resources :users, except: :show

  get "/:server/:riot_id", to: "summoners#show", as: :summoner
  # get "/:server/:riot_id/edit", to: "summoners#edit", as: :edit_summoner
  # patch "/:server/:riot_id", to: "summoners#update"
  # put "/:server/:riot_id", to: "summoners#update"
  delete "/:server/:riot_id", to: "summoners#destroy"
  resources :summoners, except: [:show, :edit, :update, :destroy]

  get "/:server/:riot_id/:game_num", to: "games#show", as: :game
  # get "/:server/:riot_id/:game_num/edit", to: "games#edit", as: :edit_game
  # patch "/:server/:riot_id/:game_num", to: "games#update"
  # put "/:server/:riot_id/:game_num", to: "games#update"
  delete "/:server/:riot_id/:game_num", to: "games#destroy"
  resources :games, except: [:show, :edit, :update, :destroy]
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="left">
      <% if user_signed_in? %>
        <li><%= link_to 'Dashboard', dashboard_path %></li>
      <% end %>
      <% if user_signed_in? %>
        <% if current_user.has_role? :admin %>
          <li><%= link_to 'Admin', users_path %></li>
        <% end %>
      <% end %>
    </ul>
    <ul class="right">
      <% if user_signed_in? %>
        <li><%= link_to 'Edit account', edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
      <% if user_signed_in? %>
        <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
      <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <li><%= link_to 'Admin', users_path %></li>
  <% end %>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Dashboard', dashboard_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "League Stats" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "League Stats" %>">
    <%= stylesheet_link_tag "application" %>
    <%# Foundation 5 won't work with Rails Turbolinks %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%# Foundation 5 won't work when application.js is included in HEAD %>
    <%= javascript_include_tag "application" %>
  </body>
</html>